---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mydatabase
    app: database
  name: mydatabase
spec:
  containers:
  - image: mysql:latest
    name: mydatabase
    ports:
    - containerPort: 3306
    resources: {}
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    volumeMounts:
      - mountPath: "var/lib/mysql"
        name: mysql-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: mysql-volume
      persistentVolumeClaim:
        claimName: database-persistent-volume-claim
  
status: {}
