---
apiVersion: v1
kind: Service
metadata:
  name: appreactnodeport
spec:
  ports:
  - nodePort: 30808
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: appreact
  type: NodePort
status:
  loadBalancer: {}